workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

stages:
  - release

publish:
  image: node:17-alpine
  stage: release
  script:
    - yarn install
    - yarn build
    - yarn semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
